GoNoGo/force-app/main/default/objects/Go_No_Go_Answer__c/Go_No_Go_Answer__c.object-meta.xml
<CustomObject>
    <description>This object stores Go/No-Go Score as well as Go/No-Go Status for answers given by the user.</description>
    <label>Go/No-Go Submission</label>
    <nameField>
        <displayFormat>GNGA-{0000}</displayFormat>
        <label>Go/No-Go Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Go/No-Go Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Answer__c/fields/Go_No_Go_Score__c.field-meta.xml
<CustomField>
    <fullName>Go_No_Go_Score__c</fullName>
    <description>Stores the Go/No-Go Score.</description>
    <label>Final Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Answer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Go/No-Go Submissions</relationshipLabel>
    <relationshipName>Go_No_Go_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/GoNoGoSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>To set default configurations for Go/No-Go.</description>
    <label>Loopio Go/No-Go Settings</label>
</CustomObject>

GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/fields/Auto_Submit_for_Approval__c.field-meta.xml
<CustomField>
    <fullName>Auto_Submit_for_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To send Go/No-Go for approval automatically if the score is below threshold value.</description>
    <label>Auto Submit for Approval</label>
    <type>Checkbox</type>
</CustomField>

GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/fields/Default_Configuration_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Configuration_Name__c</fullName>
    <description>Stores default configuration name which will open on click of Go/No-Go button on salesforce opportunity.</description>
    <label>Default Configuration Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/fields/Disable_Answer_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_Answer_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is created from a developer point of view while importing large amounts of data.</description>
    <label>Disable Answer Trigger</label>
    <type>Checkbox</type>
</CustomField>

GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/fields/Threshold_Score_for_Approval__c.field-meta.xml
<CustomField>
    <fullName>Threshold_Score_for_Approval__c</fullName>
    <description>Threshold score for sending Go/No-Go for approval.</description>
    <label>Threshold Score for Approval</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GoNoGo/force-app/main/default/classes/GoNoGoAnswerTriggerTest.cls
@isTest
public with sharing class GoNoGoAnswerTriggerTest {

    @TestSetup
    static void setup() {
        Profile p = [select id from profile where name='System Administrator'];
        String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        String randomString = '';
        while (randomString.length() < 10) {
           Integer index = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
           randomString += chars.substring(index, index+1);
        }
        String uname = 'test' + randomString + '@testEmail.com';
        User u = new User(alias = 'ftestusr', 
            email='test@loopio.com', 
            emailencodingkey='UTF-8', 
            firstname ='Testing',
            lastname='Testing', 
            languagelocalekey='en_US', 
            localesidkey='en_US', 
            profileid = p.Id, 
            isActive = true,
            timezonesidkey='America/Los_Angeles', 
            username = uname); 
        insert u;
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Go_No_Go_Permission_set'];
        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id);
    }

    @isTest
    public static void updateAnswerTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Opportunity opp = new Opportunity();
            opp.Closedate= System.today();
            opp.Name = 'test';
            opp.StageName = 'IsWon';
            insert opp;
            
            Go_No_Go_Answer__c answer = new Go_No_Go_Answer__c();
            answer.Opportunity__c = opp.Id;
            insert answer;
            
            GoNoGoSetting__c gonogosetting = GoNoGoSetting__c.getOrgDefaults();
            gonogosetting.Disable_Answer_Trigger__c = false;
            gonogosetting.Auto_Submit_for_Approval__c = true;
            gonogosetting.Threshold_Score_for_Approval__c = 50;
            gonogosetting.Default_Configuration_Name__c = 'Test';
            insert gonogosetting;
            
            answer.Go_No_Go_Score__c = 30;
            update answer;

            List<ProcessInstance> approvalSentList = [SELECT Id, TargetObjectId FROM ProcessInstance WHERE Status = 'Pending' and TargetObjectId IN (select id from Go_No_Go_Answer__c where id = :answer.Id)];
            System.Assert(approvalSentList !=  null);
        }
    }
}