GoNoGo/force-app/main/default/objects/Go_No_Go_Answer__c/Go_No_Go_Answer__c.object-meta.xml
<CustomObject>
    <description>This object stores Go/No-Go Score as well as Go/No-Go Status for answers given by the user.</description>
    <label>Go/No-Go Submission</label>
    <nameField>
        <displayFormat>GNGA-{0000}</displayFormat>
        <label>Go/No-Go Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Go/No-Go Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Answer__c/fields/Go_No_Go_Score__c.field-meta.xml
<CustomField>
    <fullName>Go_No_Go_Score__c</fullName>
    <description>Stores the Go/No-Go Score.</description>
    <label>Final Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/GoNoGoSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>To set default configurations for Go/No-Go.</description>
    <label>Loopio Go/No-Go Settings</label>
</CustomObject>

GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/fields/Auto_Submit_for_Approval__c.field-meta.xml
<CustomField>
    <fullName>Auto_Submit_for_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To send Go/No-Go for approval automatically if the score is below threshold value.</description>
    <label>Auto Submit for Approval</label>
    <type>Checkbox</type>
</CustomField>

GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/fields/Disable_Answer_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_Answer_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is created from a developer point of view while importing large amounts of data.</description>
    <label>Disable Answer Trigger</label>
    <type>Checkbox</type>
</CustomField>

GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/fields/Threshold_Score_for_Approval__c.field-meta.xml
<CustomField>
    <fullName>Threshold_Score_for_Approval__c</fullName>
    <description>Threshold score for sending Go/No-Go for approval.</description>
    <label>Threshold Score for Approval</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GoNoGo/force-app/main/default/classes/GoNoGoAnswerTriggerController.cls
/*

*@description: This is handler class for GoNoGoAnswerTrigger.

*/
public with sharing class GoNoGoAnswerTriggerController {
    /*

    @description: This method is used to send go no go answer record for approval

    @param dateInput: Pass list of Go_No_Go_Answer__c records

    @return void

    */
    public static void sendForApproval(List<Go_No_Go_Answer__c> newItems){
        GoNoGoSetting__c gonogosetting = GoNoGoSetting__c.getorgdefaults();
        if(gonogosetting != null && !gonogosetting.Disable_Answer_Trigger__c && gonogosetting.Auto_Submit_for_Approval__c && gonogosetting.Threshold_Score_for_Approval__c != null){
            Integer thresholdvalue = Integer.valueOf(gonogosetting.Threshold_Score_for_Approval__c);
            for(Go_No_Go_Answer__c gonogoanswer : newItems){
                if(gonogoanswer.Go_No_Go_Score__c == null || Integer.valueOf(gonogoanswer.Go_No_Go_Score__c) <= thresholdvalue){
                    Boolean result = GoNoGoController.submitForApproval(String.valueOf(gonogoanswer.Id));
                }
            }
        }
    }
}