GoNoGo/force-app/main/default/objects/Go_No_Go_Answer__c/Go_No_Go_Answer__c.object-meta.xml
<CustomObject>
    <description>This object stores Go/No-Go Score as well as Go/No-Go Status for answers given by the user.</description>
    <label>Go/No-Go Submission</label>
    <nameField>
        <displayFormat>GNGA-{0000}</displayFormat>
        <label>Go/No-Go Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Go/No-Go Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Answer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Go/No-Go Submissions</relationshipLabel>
    <relationshipName>Go_No_Go_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

GoNoGo/force-app/main/default/classes/GonogodetailControllerTest.cls
@IsTest
public with sharing class GonogodetailControllerTest {

    @IsTest
    static void testProjectQuestionListController_Custom(){
       	Opportunity opp = new Opportunity();
        opp.Closedate= System.today();
        opp.Name = 'test';
        opp.StageName = 'IsWon';
        insert opp;
        
        Go_No_Go_Answer__c answer = new Go_No_Go_Answer__c();
        answer.Opportunity__c = opp.Id;
        insert answer;
        
       	GonogodetailController gng = new GonogodetailController();
       	gng.recordId = answer.Id;
        System.assert(gng.projectSO != null);
    }
}