GoNoGo/force-app/main/default/objects/Go_No_Go_Answer__c/Go_No_Go_Answer__c.object-meta.xml
<CustomObject>
    <description>This object stores Go/No-Go Score as well as Go/No-Go Status for answers given by the user.</description>
    <label>Go/No-Go Submission</label>
    <nameField>
        <displayFormat>GNGA-{0000}</displayFormat>
        <label>Go/No-Go Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Go/No-Go Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Answer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Go/No-Go Submissions</relationshipLabel>
    <relationshipName>Go_No_Go_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Answer__c/fields/Status_Label__c.field-meta.xml
<CustomField>
    <fullName>Status_Label__c</fullName>
    <label>Status Label</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Configuration__c/Go_No_Go_Configuration__c.object-meta.xml
<CustomObject>
    <description>This object stores a master record of Go/No-Go configuration.</description>
    <label>Go/No-Go Configuration</label>
    <nameField>
        <label>Go/No-Go Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Go/No-Go Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Linked_Configuration__c/Go_No_Go_Linked_Configuration__c.object-meta.xml
<CustomObject>
    <label>Go/No-Go Linked Configuration</label>
    <nameField>
        <label>Go/No-Go Linked Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Go/No-Go Linked Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Linked_Configuration__c/fields/Go_No_Go_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Go_No_Go_Configuration__c</fullName>
    <label>Go/No-Go Configuration</label>
    <referenceTo>Go_No_Go_Configuration__c</referenceTo>
    <relationshipLabel>Go/No-Go Linked Configurations</relationshipLabel>
    <relationshipName>Go_No_Go_Linked_Configurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/GoNoGoSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>To set default configurations for Go/No-Go.</description>
    <label>Loopio Go/No-Go Settings</label>
</CustomObject>

GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/fields/Default_Configuration_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Configuration_Name__c</fullName>
    <description>Stores default configuration name which will open on click of Go/No-Go button on salesforce opportunity.</description>
    <label>Default Configuration Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

GoNoGo/force-app/main/default/classes/SendNotificationQueue.cls
public class SendNotificationQueue implements Queueable, Database.AllowsCallouts {
    public static Id currentOpportunityId;
    public static Id answerId;
    Set<Id> oppIds = new Set<Id>();
    
    public SendNotificationQueue(Set<Id> oppIds) {
        this.oppIds = oppIds;
    }

    public void execute(QueueableContext context) {
        try{
            Map<Id,Id> configIdsToOwnerMap = new Map<Id,Id>();
            GoNoGoSetting__c gonogosetting = GoNoGoSetting__c.getOrgDefaults();
            String defaultConfigName;
            if(gonogosetting != null){
                defaultConfigName = gonogosetting.Default_Configuration_Name__c;
            }
            List<Go_No_Go_Linked_Configuration__c> linkedConfigs = [select id, Go_No_Go_Configuration__c, Go_No_Go_Configuration__r.OwnerId from Go_No_Go_Linked_Configuration__c WITH SECURITY_ENFORCED];
            if(linkedConfigs != null && linkedConfigs.size() > 0){
                for(Go_No_Go_Linked_Configuration__c lc : linkedConfigs){
                    configIdsToOwnerMap.put(lc.Go_No_Go_Configuration__c, lc.Go_No_Go_Configuration__r.OwnerId);
                }
            }
            else if(defaultConfigName != null && String.isNotBlank(defaultConfigName)){
                Go_No_Go_Configuration__c configRec = [select id, ownerId from Go_No_Go_Configuration__c WHERE Name = :defaultConfigName WITH SECURITY_ENFORCED order by createddate asc limit 1];
                if(configRec != null){
                    configIdsToOwnerMap.put(configRec.Id, configRec.ownerId);
                }
            }
            
            if(configIdsToOwnerMap.size() > 0){
                String emailTemplateName = 'Go/No Go Submission Notification Email Template';
                EmailTemplate et = [SELECT Id FROM EmailTemplate WHERE name =:emailTemplateName];
                List<Messaging.SingleEmailMessage> emailMessageList = new List<Messaging.SingleEmailMessage>();
                for (string oppId : oppIds) {
                    currentOpportunityId = oppId;
                    break;
                }
                //if(configIdsToOwnerMap.size() > 1){
                    Go_No_Go_Answer__c answer = new Go_No_Go_Answer__c();
                    answer.Opportunity__c = currentOpportunityId;
                    answer.Status_Label__c = 'Pending';
                    insert answer;
                    answerId = answer.Id;
                //}
                oppIds.remove(currentOpportunityId);
                for(Id configId : configIdsToOwnerMap.keySet()){
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
                    mail.setTargetObjectId(configIdsToOwnerMap.get(configId));
                    mail.setTemplateId(et.id); 
                    mail.setWhatId(configId); 
                    mail.setBccSender(false); 
                    mail.setUseSignature(false); 
                    mail.setSaveAsActivity(false);
                    emailMessageList.add(mail);                            
                }
                if(emailMessageList.size() > 0){
                    Messaging.sendEmail(emailMessageList);
                }
                
                if(oppIds.size() > 0){
                    System.enqueueJob(new SendNotificationQueue(oppIds));
                }
            }
        }catch(Exception callException){}
    }
}