GoNoGo/force-app/main/default/objects/Go_No_Go_Answer__c/Go_No_Go_Answer__c.object-meta.xml
<CustomObject>
    <description>This object stores Go/No-Go Score as well as Go/No-Go Status for answers given by the user.</description>
    <label>Go/No-Go Submission</label>
    <nameField>
        <displayFormat>GNGA-{0000}</displayFormat>
        <label>Go/No-Go Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Go/No-Go Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Answer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Go/No-Go Submissions</relationshipLabel>
    <relationshipName>Go_No_Go_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Answer__c/fields/Static_Resource_Name__c.field-meta.xml
<CustomField>
    <fullName>Static_Resource_Name__c</fullName>
    <description>To store static resource name for color.</description>
    <label>Static Resource Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Answer_Item__c/Go_No_Go_Answer_Item__c.object-meta.xml
<CustomObject>
    <description>This object stores the actual record or Go/No-Go answers which stores answers given by the users. This object contains a Master-Detail relation with the Go/No-Go Answer object.</description>
    <label>Go/No-Go Question &amp; Answer Value</label>
    <nameField>
        <displayFormat>GNGAI-{0000}</displayFormat>
        <label>Go/No-Go Q&amp;A Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Go/No-Go Question &amp; Answer Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Answer_Item__c/fields/Go_No_Go_Answer__c.field-meta.xml
<CustomField>
    <fullName>Go_No_Go_Answer__c</fullName>
    <description>Master-Detail relation with Go/No-Go Submission.</description>
    <label>Go/No-Go Submission</label>
    <referenceTo>Go_No_Go_Answer__c</referenceTo>
    <relationshipLabel>Go/No-Go Question &amp; Answer Values</relationshipLabel>
    <relationshipName>Go_No_Go_Answer_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Answer_Item__c/fields/Go_No_Go_Question_Bank__c.field-meta.xml
<CustomField>
    <fullName>Go_No_Go_Question_Bank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup of Go/No-Go Question Bank for actual question.</description>
    <label>Go/No-Go Question</label>
    <referenceTo>Go_No_Go_Question_Bank__c</referenceTo>
    <relationshipLabel>Go/No-Go Question &amp; Answer Values</relationshipLabel>
    <relationshipName>Go_No_Go_Answer_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Answer_Item__c/fields/Go_No_Go_Question_Bank_Scoring__c.field-meta.xml
<CustomField>
    <fullName>Go_No_Go_Question_Bank_Scoring__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup of Go/No-Go Question Bank Scoring for getting actual score for that answer.</description>
    <label>Go/No-Go Question Scoring</label>
    <referenceTo>Go_No_Go_Question_Bank_Scoring__c</referenceTo>
    <relationshipLabel>Go/No-Go Question &amp; Answer Values</relationshipLabel>
    <relationshipName>Go_No_Go_Answer_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Answer_Item__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <formula>Go_No_Go_Question_Bank_Scoring__r.Score__c</formula>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Answer_Item__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>To store answer given by the user.</description>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Configuration__c/Go_No_Go_Configuration__c.object-meta.xml
<CustomObject>
    <description>This object stores a master record of Go/No-Go configuration.</description>
    <label>Go/No-Go Configuration</label>
    <nameField>
        <label>Go/No-Go Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Go/No-Go Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Linked_Configuration__c/Go_No_Go_Linked_Configuration__c.object-meta.xml
<CustomObject>
    <label>Go/No-Go Linked Configuration</label>
    <nameField>
        <label>Go/No-Go Linked Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Go/No-Go Linked Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Linked_Configuration__c/fields/Go_No_Go_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Go_No_Go_Configuration__c</fullName>
    <label>Go/No-Go Configuration</label>
    <referenceTo>Go_No_Go_Configuration__c</referenceTo>
    <relationshipLabel>Go/No-Go Linked Configurations</relationshipLabel>
    <relationshipName>Go_No_Go_Linked_Configurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Linked_Submission__c/Go_No_Go_Linked_Submission__c.object-meta.xml
<CustomObject>
    <label>Go/No-Go Linked Submission</label>
    <nameField>
        <displayFormat>GNGLS-{0000}</displayFormat>
        <label>Go/No-Go Linked Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Go/No-Go Linked Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Linked_Submission__c/fields/Go_No_Go_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Go_No_Go_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Go/No-Go Configuration</label>
    <referenceTo>Go_No_Go_Configuration__c</referenceTo>
    <relationshipLabel>Go/No-Go Linked Submissions</relationshipLabel>
    <relationshipName>Go_No_Go_Linked_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Linked_Submission__c/fields/Go_No_Go_Submission__c.field-meta.xml
<CustomField>
    <fullName>Go_No_Go_Submission__c</fullName>
    <label>Go/No-Go Submission</label>
    <referenceTo>Go_No_Go_Answer__c</referenceTo>
    <relationshipLabel>Go/No-Go Linked Submissions</relationshipLabel>
    <relationshipName>Go_No_Go_Linked_Submissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Question_Bank__c/Go_No_Go_Question_Bank__c.object-meta.xml
<CustomObject>
    <description>These records store actual questions which are going to be displayed on the Go/No-Go screen.</description>
    <label>Go/No-Go Question</label>
    <nameField>
        <displayFormat>GNGQB-{0000}</displayFormat>
        <label>Go/No-Go Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Go/No-Go Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Question_Bank__c/fields/Go_No_Go_Section__c.field-meta.xml
<CustomField>
    <fullName>Go_No_Go_Section__c</fullName>
    <description>Master-Detail relation with Go/No-Go Section.</description>
    <label>Go/No-Go Section</label>
    <referenceTo>Go_No_Go_Section__c</referenceTo>
    <relationshipLabel>Go/No-Go Questions</relationshipLabel>
    <relationshipName>Go_No_Go_Question_Banks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Question_Bank__c/fields/Question_Label__c.field-meta.xml
<CustomField>
    <fullName>Question_Label__c</fullName>
    <description>Stores actual question which will be displayed.</description>
    <label>Question Label</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Question_Bank_Scoring__c/Go_No_Go_Question_Bank_Scoring__c.object-meta.xml
<CustomObject>
    <description>Stores scoring for each question.</description>
    <label>Go/No-Go Question Response</label>
    <nameField>
        <displayFormat>GNGQBS-{0000}</displayFormat>
        <label>Go/No-Go Question Scoring Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Go/No-Go Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Question_Bank_Scoring__c/fields/Go_No_Go_Question_Bank__c.field-meta.xml
<CustomField>
    <fullName>Go_No_Go_Question_Bank__c</fullName>
    <description>Master-Detail relation with Go/No-Go Question Bank.</description>
    <label>Go/No-Go Question</label>
    <referenceTo>Go_No_Go_Question_Bank__c</referenceTo>
    <relationshipLabel>Go/No-Go Question Responses</relationshipLabel>
    <relationshipName>Go_No_Go_Question_Bank_Scorings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Question_Bank_Scoring__c/fields/Max_Range__c.field-meta.xml
<CustomField>
    <fullName>Max_Range__c</fullName>
    <description>Expected value of answer (required when Comparison Type of related Go/No-Go Question Bank is Range)</description>
    <label>Max Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Question_Bank_Scoring__c/fields/Min_Range__c.field-meta.xml
<CustomField>
    <fullName>Min_Range__c</fullName>
    <description>Expected value of answer (required when Comparison Type of related Go/No-Go Question Bank is Range)</description>
    <label>Min Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Question_Bank_Scoring__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>Stores score of the answer.</description>
    <inlineHelpText>The value added to the final Go/No-Go Score when this response is selected. This score cannot exceed the question&apos;s max score.</inlineHelpText>
    <label>Score</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Question_Bank_Scoring__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Expected value of answer (required when Comparison Type of related Go/No-Go Question Bank is Value)</description>
    <label>Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Section__c/Go_No_Go_Section__c.object-meta.xml
<CustomObject>
    <description>There can be multiple sections in a Go/No-Go flow. Each section can consist of different sets of questions. To store the sections, we are going to use this object.</description>
    <label>Go/No-Go Section</label>
    <nameField>
        <label>Go/No-Go Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Go/No-Go Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Section__c/fields/Go_No_Go_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Go_No_Go_Configuration__c</fullName>
    <description>Master-Detail relation with Go/No-Go Configuration.</description>
    <label>Go/No-Go Configuration</label>
    <referenceTo>Go_No_Go_Configuration__c</referenceTo>
    <relationshipLabel>Go/No-Go Sections</relationshipLabel>
    <relationshipName>Go_No_Go_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/GoNoGoSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>To set default configurations for Go/No-Go.</description>
    <label>Loopio Go/No-Go Settings</label>
</CustomObject>

GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/fields/Auto_Submit_for_Approval__c.field-meta.xml
<CustomField>
    <fullName>Auto_Submit_for_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To send Go/No-Go for approval automatically if the score is below threshold value.</description>
    <label>Auto Submit for Approval</label>
    <type>Checkbox</type>
</CustomField>

GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/fields/Default_Configuration_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Configuration_Name__c</fullName>
    <description>Stores default configuration name which will open on click of Go/No-Go button on salesforce opportunity.</description>
    <label>Default Configuration Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/fields/Threshold_Score_for_Approval__c.field-meta.xml
<CustomField>
    <fullName>Threshold_Score_for_Approval__c</fullName>
    <description>Threshold score for sending Go/No-Go for approval.</description>
    <label>Threshold Score for Approval</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GoNoGo/force-app/main/default/objects/GoNoGoStatus__c/GoNoGoStatus__c.object-meta.xml
<CustomObject>
    <label>Go/No-Go Status</label>
    <nameField>
        <label>Go/No-Go Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Go/No-Go Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/GoNoGoStatus__c/fields/Max_Range__c.field-meta.xml
<CustomField>
    <fullName>Max_Range__c</fullName>
    <label>Max Range</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GoNoGo/force-app/main/default/objects/GoNoGoStatus__c/fields/Min_Range__c.field-meta.xml
<CustomField>
    <fullName>Min_Range__c</fullName>
    <label>Min Range</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GoNoGo/force-app/main/default/classes/GoNoGoControllerTest.cls
@isTest
public with sharing class GoNoGoControllerTest {


    @TestSetup
    static void setup(){
        Profile p = [select id from profile where name='System Administrator'];
        String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        String randomString = '';
        while (randomString.length() < 10) {
           Integer index = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
           randomString += chars.substring(index, index+1);
        }
        String uname = 'test' + randomString + '@testEmail.com';
        User u = new User(alias = 'ftestusr', 
            email='test@loopio.com', 
            emailencodingkey='UTF-8', 
            firstname ='Testing',
            lastname='Testing', 
            languagelocalekey='en_US', 
            localesidkey='en_US', 
            profileid = p.Id, 
            isActive = true,
            timezonesidkey='America/Los_Angeles', 
            username = uname); 
        insert u;
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Go_No_Go_Permission_set'];
        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id);
    }

    @isTest
    public static void getGoNoGOQuestionsFromConfigurationTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Go_No_Go_Configuration__c config = new Go_No_Go_Configuration__c();
            config.Name = 'Test Config';
            insert config;
            
            Go_No_Go_Section__c section = new Go_No_Go_Section__c();
            section.Name = 'Test Section';
            section.Go_No_Go_Configuration__c = config.Id;
            insert section;
            
            Go_No_Go_Question_Bank__c question = new Go_No_Go_Question_Bank__c();
            question.Go_No_Go_Section__c = section.Id;
            question.Question_Label__c = 'Test Question';
            insert question;
            
            Go_No_Go_Question_Bank_Scoring__c scoring = new Go_No_Go_Question_Bank_Scoring__c();
            scoring.Go_No_Go_Question_Bank__c = question.Id;
            scoring.Score__c = 1;
            scoring.Value__c = 'Yes';
            insert scoring;
            
            List<GoNoGoController.SectionWrapper> response = GoNoGoController.getGoNoGOQuestionsFromConfiguration(config.Name,null);
            System.Assert(response != null);
        }
    }

    @isTest
    public static void getGoNoGOQuestionsFromConfigurationTest2(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Go_No_Go_Configuration__c config = new Go_No_Go_Configuration__c();
            config.Name = 'Test Config';
            insert config;
            
            Go_No_Go_Section__c section = new Go_No_Go_Section__c();
            section.Name = 'Test Section';
            section.Go_No_Go_Configuration__c = config.Id;
            insert section;
            
            Go_No_Go_Question_Bank__c question = new Go_No_Go_Question_Bank__c();
            question.Go_No_Go_Section__c = section.Id;
            question.Question_Label__c = 'Test Question';
            insert question;
            
            Go_No_Go_Question_Bank_Scoring__c scoring = new Go_No_Go_Question_Bank_Scoring__c();
            scoring.Go_No_Go_Question_Bank__c = question.Id;
            scoring.Score__c = 1;
            scoring.Value__c = 'Yes';
            insert scoring;

            Opportunity opp = new Opportunity();
            opp.Closedate= System.today();
            opp.Name = 'test';
            opp.StageName = 'IsWon';
            insert opp;
            
            Go_No_Go_Answer__c answer = new Go_No_Go_Answer__c();
            answer.Opportunity__c = opp.Id;
            insert answer;
            
            List<GoNoGoController.SectionWrapper> response = GoNoGoController.getGoNoGOQuestionsFromConfiguration(config.Name,answer.Id);
            System.Assert(response != null);
        }
    }
    
    @isTest
    public static void saveAnswerRecordsTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Go_No_Go_Configuration__c config = new Go_No_Go_Configuration__c();
            config.Name = 'Test Config';
            insert config;
            
            Go_No_Go_Section__c section = new Go_No_Go_Section__c();
            section.Name = 'Test Section';
            section.Go_No_Go_Configuration__c = config.Id;
            insert section;
            
            Go_No_Go_Question_Bank__c question = new Go_No_Go_Question_Bank__c();
            question.Go_No_Go_Section__c = section.Id;
            question.Question_Label__c = 'Test Question';
            insert question;
            
            Go_No_Go_Question_Bank_Scoring__c scoring = new Go_No_Go_Question_Bank_Scoring__c();
            scoring.Go_No_Go_Question_Bank__c = question.Id;
            scoring.Score__c = 1;
            scoring.Value__c = 'Yes';
            insert scoring;
            
            List<GoNoGoController.ScoringWrapper> scoringRecords = new List<GoNoGoController.ScoringWrapper>();
            GoNoGoController.ScoringWrapper scoreWrapper = new GoNoGoController.ScoringWrapper();
            scoreWrapper.scoringId = scoring.Id;
            scoreWrapper.value = 'anse';
            scoreWrapper.score = 1;
            scoringRecords.add(scoreWrapper);
            
            List<GoNoGoController.QuestionWrapper> questionRecords = new List<GoNoGoController.QuestionWrapper>();
            GoNoGoController.QuestionWrapper quesWrapper = new GoNoGoController.QuestionWrapper();
            quesWrapper.questionId = question.Id;
            quesWrapper.questionLabel = question.Question_Label__c;
            quesWrapper.questionSequence = 1;
            quesWrapper.sectionId = section.Id;
            quesWrapper.answerValue = 'anse';
            quesWrapper.maxScore = 3;
            questionRecords.add(quesWrapper);
            quesWrapper.scoringRecords = scoringRecords;
            
            List<GoNoGoController.SectionWrapper> sectionWrapperList = new List<GoNoGoController.SectionWrapper>();
            GoNoGoController.SectionWrapper sectionWrapper = new GoNoGoController.SectionWrapper();
            sectionWrapper.sectionId = section.Id;
            sectionWrapper.sectionName = section.Name;
            sectionWrapper.sectionSequence = 1;
            sectionWrapper.questionRecords = questionRecords;
            sectionWrapperList.add(sectionWrapper);
            
            Opportunity opp = new Opportunity();
            opp.Closedate= System.today();
            opp.Name = 'test';
            opp.StageName = 'IsWon';
            insert opp;
            
            GoNoGoController.ResultWrapper response = GoNoGoController.saveAnswerRecords(JSON.serialize(sectionWrapperList),String.valueOf(opp.id),null);
            System.Assert(response != null);
        }
    }

    @isTest
    public static void saveAnswerRecordsTest1(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Go_No_Go_Configuration__c config = new Go_No_Go_Configuration__c();
            config.Name = 'Test Config';
            insert config;
            
            Go_No_Go_Section__c section = new Go_No_Go_Section__c();
            section.Name = 'Test Section';
            section.Go_No_Go_Configuration__c = config.Id;
            insert section;
            
            Go_No_Go_Question_Bank__c question = new Go_No_Go_Question_Bank__c();
            question.Go_No_Go_Section__c = section.Id;
            question.Question_Label__c = 'Test Question';
            insert question;
            
            Go_No_Go_Question_Bank_Scoring__c scoring = new Go_No_Go_Question_Bank_Scoring__c();
            scoring.Go_No_Go_Question_Bank__c = question.Id;
            scoring.Score__c = 1;
            scoring.Value__c = 'Yes';
            insert scoring;
            
            List<GoNoGoController.ScoringWrapper> scoringRecords = new List<GoNoGoController.ScoringWrapper>();
            GoNoGoController.ScoringWrapper scoreWrapper = new GoNoGoController.ScoringWrapper();
            scoreWrapper.scoringId = scoring.Id;
            scoreWrapper.value = 'anse';
            scoreWrapper.score = 1;
            scoringRecords.add(scoreWrapper);
            
            List<GoNoGoController.QuestionWrapper> questionRecords = new List<GoNoGoController.QuestionWrapper>();
            GoNoGoController.QuestionWrapper quesWrapper = new GoNoGoController.QuestionWrapper();
            quesWrapper.questionId = question.Id;
            quesWrapper.questionLabel = question.Question_Label__c;
            quesWrapper.questionSequence = 1;
            quesWrapper.sectionId = section.Id;
            quesWrapper.answerValue = 'anse';
            quesWrapper.maxScore = 3;
            questionRecords.add(quesWrapper);
            quesWrapper.scoringRecords = scoringRecords;
            
            List<GoNoGoController.SectionWrapper> sectionWrapperList = new List<GoNoGoController.SectionWrapper>();
            GoNoGoController.SectionWrapper sectionWrapper = new GoNoGoController.SectionWrapper();
            sectionWrapper.sectionId = section.Id;
            sectionWrapper.sectionName = section.Name;
            sectionWrapper.sectionSequence = 1;
            sectionWrapper.questionRecords = questionRecords;
            sectionWrapperList.add(sectionWrapper);
            
            Opportunity opp = new Opportunity();
            opp.Closedate= System.today();
            opp.Name = 'test';
            opp.StageName = 'IsWon';
            insert opp;
            
            Go_No_Go_Answer__c answer = new Go_No_Go_Answer__c();
            answer.Opportunity__c = opp.Id;
            insert answer;

            Go_No_Go_Linked_Configuration__c linkedconfig = new Go_No_Go_Linked_Configuration__c();
            linkedconfig.Name = 'Test Linked';
            linkedconfig.Go_No_Go_Configuration__c = config.Id;
            insert linkedconfig;

            GoNoGoController.ResultWrapper response = GoNoGoController.saveAnswerRecords(JSON.serialize(sectionWrapperList),answer.Id,linkedconfig.Id);
            System.Assert(response != null);
        }
    }
    
    @isTest
    public static void submitForApprovalTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Opportunity opp = new Opportunity();
            opp.Closedate= System.today();
            opp.Name = 'test';
            opp.StageName = 'IsWon';
            insert opp;
            
            Go_No_Go_Answer__c answer = new Go_No_Go_Answer__c();
            answer.Opportunity__c = opp.Id;
            insert answer;
            
            Boolean response = GoNoGoController.submitForApproval(String.valueOf(answer.id));
            System.Assert(response != null);
        }
    }
    
    @isTest
    public static void checkIfApprovedTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Opportunity opp = new Opportunity();
            opp.Closedate= System.today();
            opp.Name = 'test';
            opp.StageName = 'IsWon';
            insert opp;
            
            Go_No_Go_Answer__c answer = new Go_No_Go_Answer__c();
            answer.Opportunity__c = opp.Id;
            insert answer;
            
            GoNoGoController.ResultWrapper response = GoNoGoController.checkIfApproved(String.valueOf(answer.id));
            System.Assert(response != null);
        }
    }
    
    @isTest
    public static void getDefaultConfigurationsTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Go_No_Go_Configuration__c config = new Go_No_Go_Configuration__c();
            config.Name = 'Test Config';
            insert config;
            
            Go_No_Go_Section__c section = new Go_No_Go_Section__c();
            section.Name = 'Test Section';
            section.Go_No_Go_Configuration__c = config.Id;
            insert section;
            
            Go_No_Go_Question_Bank__c question = new Go_No_Go_Question_Bank__c();
            question.Go_No_Go_Section__c = section.Id;
            question.Question_Label__c = 'Test Question';
            insert question;
            
            Go_No_Go_Question_Bank_Scoring__c scoring = new Go_No_Go_Question_Bank_Scoring__c();
            scoring.Go_No_Go_Question_Bank__c = question.Id;
            scoring.Score__c = 1;
            scoring.Value__c = 'Yes';
            insert scoring;
            
            GoNoGoSetting__c gonogosetting = GoNoGoSetting__c.getorgdefaults();
            gonogosetting.Default_Configuration_Name__c = 'Test Config';
            gonogosetting.Threshold_Score_for_Approval__c = 40;
            Database.upsert(gonogosetting);
            
            List<GoNoGoStatus__c> statusList = new List<GoNoGoStatus__c>();
            GoNoGoStatus__c status1 = new  GoNoGoStatus__c();
            status1.Name = 'Red';
            status1.Min_Range__c = 0;
            status1.Max_Range__c = 30;
            status1.Static_Resource_Name__c = 'red_status';
            statusList.add(status1);
    
            GoNoGoStatus__c status2 = new  GoNoGoStatus__c();
            status2.Name = 'Yellow';
            status2.Min_Range__c = 31;
            status2.Max_Range__c = 60;
            status2.Static_Resource_Name__c = 'yellow_status';
            statusList.add(status2);
            
            Database.insert(statusList,true);
            
            GoNoGoController.GoNoGoSettingsWrapper response = GoNoGoController.getDefaultConfigurations();
            System.Assert(response != null);
        }
    }
    
    @isTest
    public static void updateDefaultConfigNameTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            
            GoNoGoSetting__c gonogosetting = GoNoGoSetting__c.getorgdefaults();
            gonogosetting.Default_Configuration_Name__c = 'Test Config';
            gonogosetting.Threshold_Score_for_Approval__c = 40;
            Database.upsert(gonogosetting);
            
            GoNoGoController.ResultWrapper response = GoNoGoController.updateDefaultConfigName('Test 2');
            GoNoGoSetting__c gonogosetting1 = GoNoGoSetting__c.getorgdefaults();
            System.Assert(gonogosetting1.Default_Configuration_Name__c == 'Test 2');
        }
    }
    
    @isTest
    public static void updateThresholdTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            
            GoNoGoSetting__c gonogosetting = GoNoGoSetting__c.getorgdefaults();
            gonogosetting.Default_Configuration_Name__c = 'Test Config';
            gonogosetting.Threshold_Score_for_Approval__c = 40;
            Database.upsert(gonogosetting);
            
            GoNoGoController.ResultWrapper response = GoNoGoController.updateThreshold(30,false);
            GoNoGoSetting__c gonogosetting1 = GoNoGoSetting__c.getorgdefaults();
            System.Assert(gonogosetting1.Threshold_Score_for_Approval__c == 30);
            System.Assert(gonogosetting1.Auto_Submit_for_Approval__c == false);
        }
    }
    
    @isTest
    public static void updateStatusValuesTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            
            List<GoNoGoStatus__c> statusList = new List<GoNoGoStatus__c>();
            GoNoGoStatus__c status1 = new  GoNoGoStatus__c();
            status1.Name = 'Red';
            status1.Min_Range__c = 0;
            status1.Max_Range__c = 30;
            status1.Static_Resource_Name__c = 'red_status';
            statusList.add(status1);
    
            GoNoGoStatus__c status2 = new  GoNoGoStatus__c();
            status2.Name = 'Yellow';
            status2.Min_Range__c = 31;
            status2.Max_Range__c = 60;
            status2.Static_Resource_Name__c = 'yellow_status';
            statusList.add(status2);
            
            Database.insert(statusList,true);
            
            List<GoNoGoController.GoNoGoStatusWrapper> goNoGoStatusWrapperList = new List<GoNoGoController.GoNoGoStatusWrapper>();
            List<GoNoGoStatus__c> gonogostatuslist = [select id, Name, Min_Range__c, Max_Range__c, Static_Resource_Name__c from GoNoGoStatus__c WITH SECURITY_ENFORCED limit 49999];
            if(gonogostatuslist != null && gonogostatuslist.size() > 0){
                for(GoNoGoStatus__c gonogostatus : gonogostatuslist){
                    GoNoGoController.GoNoGoStatusWrapper goNoGoStatusWrapper = new GoNoGoController.GoNoGoStatusWrapper();
                    goNoGoStatusWrapper.statusid = gonogostatus.id;
                    goNoGoStatusWrapper.label = gonogostatus.Name;
                    goNoGoStatusWrapper.minrange = gonogostatus.Min_Range__c != null ? Integer.valueOf(gonogostatus.Min_Range__c) : null;
                    goNoGoStatusWrapper.maxrange = gonogostatus.Max_Range__c != null ? Integer.valueOf(gonogostatus.Max_Range__c) : null;
                    goNoGoStatusWrapper.staticresourcename = gonogostatus.Static_Resource_Name__c;
                    goNoGoStatusWrapperList.add(goNoGoStatusWrapper);
                }
            }
            
            GoNoGoController.ResultWrapper response = GoNoGoController.updateStatusValues(JSON.serialize(goNoGoStatusWrapperList),new List<String>{String.valueOf(status2.Id)});
            System.Assert(response.isSuccess == true);
        }
    }

    @isTest
    public static void getTotalMaxScoreTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Go_No_Go_Configuration__c config = new Go_No_Go_Configuration__c();
            config.Name = 'Test Config';
            insert config;
            
            GoNoGoController.PickListWrapper response = GoNoGoController.getTotalMaxScore(config.Id);
            System.Assert(response.label == 'Configuration');

            Go_No_Go_Section__c section = new Go_No_Go_Section__c();
            section.Name = 'Test Section';
            section.Go_No_Go_Configuration__c = config.Id;
            insert section;

            GoNoGoController.PickListWrapper response1 = GoNoGoController.getTotalMaxScore(section.Id);
            System.Assert(response1.label == 'Section');
        }
    }

    @isTest
    public static void saveNewConfigurationTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            GoNoGoController.ResultWrapper response1 = GoNoGoController.saveNewConfiguration('abc',null);
            System.Assert(response1.isSuccess == true);
        }
    }

    @isTest
    public static void getSObjectListTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Opportunity opp = new Opportunity();
            opp.Closedate= System.today();
            opp.Name = 'mytest';
            opp.StageName = 'IsWon';
            insert opp;
            
            List<Opportunity> response = GoNoGoController.getSObjectList('mytest','Opportunity');
            System.Assert(response != null);
        }
    }

    @isTest
    public static void fetchDefaultRecordTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Opportunity opp = new Opportunity();
            opp.Closedate= System.today();
            opp.Name = 'mytest';
            opp.StageName = 'IsWon';
            insert opp;
            
            sObject response = GoNoGoController.fetchDefaultRecord(opp.Id,'Opportunity');
            System.Assert(response != null);
        }
    }

    @isTest
    public static void upsertQuestionRecordTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Go_No_Go_Configuration__c config = new Go_No_Go_Configuration__c();
            config.Name = 'Test Config';
            insert config;
            
            Go_No_Go_Section__c section = new Go_No_Go_Section__c();
            section.Name = 'Test Section';
            section.Go_No_Go_Configuration__c = config.Id;
            insert section;
            
            Map<String,Object> response = GoNoGoController.upsertQuestionRecord(null,section.Id,1,10,'Text','Test',false,'');
            System.Assert(response != null);
        }
    }

    @isTest
    public static void loadDataForGoNoGoQuestionTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Go_No_Go_Configuration__c config = new Go_No_Go_Configuration__c();
            config.Name = 'Test Config';
            insert config;
            
            Go_No_Go_Section__c section = new Go_No_Go_Section__c();
            section.Name = 'Test Section';
            section.Go_No_Go_Configuration__c = config.Id;
            insert section;
            
            Go_No_Go_Question_Bank__c question = new Go_No_Go_Question_Bank__c();
            question.Go_No_Go_Section__c = section.Id;
            question.Question_Label__c = 'Test Question';
            insert question;
            
            GoNoGoController.GoNoGoQuestionWrapper response = GoNoGoController.loadDataForGoNoGoQuestion(question.Id);
            System.Assert(response != null);
        }
    }

    @isTest
    public static void createLinkedConifgTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Go_No_Go_Configuration__c config = new Go_No_Go_Configuration__c();
            config.Name = 'Test Config';
            insert config;

            List<String> configIdList = new List<String>();
            configIdList.add(config.Id);
            Boolean response = GoNoGoController.createLinkedConifg('MyTest',configIdList);
            System.Assert(response == true);
        }
    }

    @isTest
    public static void getLinkedConfigsTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Go_No_Go_Configuration__c config = new Go_No_Go_Configuration__c();
            config.Name = 'Test Config';
            insert config;
            
            Go_No_Go_Linked_Configuration__c linkedconfig = new Go_No_Go_Linked_Configuration__c();
            linkedconfig.Name = 'Test Linked';
            linkedconfig.Go_No_Go_Configuration__c = config.Id;
            insert linkedconfig;

            Opportunity opp = new Opportunity();
            opp.Closedate= System.today();
            opp.Name = 'test';
            opp.StageName = 'IsWon';
            insert opp;
            
            Go_No_Go_Answer__c answer = new Go_No_Go_Answer__c();
            answer.Opportunity__c = opp.Id;
            insert answer;

            Go_No_Go_Linked_Submission__c linkedSubmission = new Go_No_Go_Linked_Submission__c();
            linkedSubmission.Go_No_Go_Submission__c = answer.Id;
            linkedSubmission.Go_No_Go_Configuration__c = config.Id;
            insert linkedSubmission;

            List<String> configIdList = new List<String>();
            configIdList.add(config.Id);
            GoNoGoController.LinkedConfigWrapperResult response = GoNoGoController.getLinkedConfigs(answer.Id,true);
            System.Assert(response != null);
        }
    }

    @isTest
    public static void getLinkedSubmissionsTest1(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Go_No_Go_Configuration__c config = new Go_No_Go_Configuration__c();
            config.Name = 'Test Config';
            insert config;
            
            Go_No_Go_Linked_Configuration__c linkedconfig = new Go_No_Go_Linked_Configuration__c();
            linkedconfig.Name = 'Test Linked';
            linkedconfig.Go_No_Go_Configuration__c = config.Id;
            insert linkedconfig;

            Opportunity opp = new Opportunity();
            opp.Closedate= System.today();
            opp.Name = 'test';
            opp.StageName = 'IsWon';
            insert opp;
            
            Go_No_Go_Answer__c answer = new Go_No_Go_Answer__c();
            answer.Opportunity__c = opp.Id;
            insert answer;

            Go_No_Go_Linked_Submission__c linkedSubmission = new Go_No_Go_Linked_Submission__c();
            linkedSubmission.Go_No_Go_Submission__c = answer.Id;
            linkedSubmission.Go_No_Go_Configuration__c = config.Id;
            insert linkedSubmission;

            List<String> configIdList = new List<String>();
            configIdList.add(config.Id);
            List<GoNoGoController.LinkedSubmissionWrapper> response = GoNoGoController.getLinkedSubmissions(answer.Id);
            System.Assert(response != null);
        }
    }

    @isTest
    public static void getLinkedSubmissionsTest2(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Go_No_Go_Configuration__c config = new Go_No_Go_Configuration__c();
            config.Name = 'Test Config';
            insert config;

            Opportunity opp = new Opportunity();
            opp.Closedate= System.today();
            opp.Name = 'test';
            opp.StageName = 'IsWon';
            insert opp;
            
            Go_No_Go_Answer__c answer = new Go_No_Go_Answer__c();
            answer.Opportunity__c = opp.Id;
            insert answer;

            List<GoNoGoController.LinkedSubmissionWrapper> response = GoNoGoController.getLinkedSubmissions(answer.Id);
            System.Assert(response != null);
        }
    }

    @isTest
    public static void getLinkedSubmissionsTest3(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Go_No_Go_Configuration__c config = new Go_No_Go_Configuration__c();
            config.Name = 'Test Config';
            insert config;

            Go_No_Go_Section__c section = new Go_No_Go_Section__c();
            section.Name = 'Test Section';
            section.Go_No_Go_Configuration__c = config.Id;
            insert section;
            
            Go_No_Go_Question_Bank__c question = new Go_No_Go_Question_Bank__c();
            question.Go_No_Go_Section__c = section.Id;
            question.Question_Label__c = 'Test Question';
            insert question;
            
            Go_No_Go_Linked_Configuration__c linkedconfig = new Go_No_Go_Linked_Configuration__c();
            linkedconfig.Name = 'Test Linked';
            linkedconfig.Go_No_Go_Configuration__c = config.Id;
            insert linkedconfig;

            Opportunity opp = new Opportunity();
            opp.Closedate= System.today();
            opp.Name = 'test';
            opp.StageName = 'IsWon';
            insert opp;
            
            Go_No_Go_Answer__c answer = new Go_No_Go_Answer__c();
            answer.Opportunity__c = opp.Id;
            insert answer;

            Go_No_Go_Answer_Item__c ansItem = new Go_No_Go_Answer_Item__c();
            ansItem.Go_No_Go_Answer__c = answer.Id;
            ansItem.Value__c = 'test';
            ansItem.Go_No_Go_Question_Bank__c = question.Id;
            insert ansItem;


            Go_No_Go_Linked_Submission__c linkedSubmission = new Go_No_Go_Linked_Submission__c();
            linkedSubmission.Go_No_Go_Submission__c = answer.Id;
            linkedSubmission.Go_No_Go_Configuration__c = config.Id;
            insert linkedSubmission;

            List<String> configIdList = new List<String>();
            configIdList.add(config.Id);
            List<GoNoGoController.LinkedSubmissionWrapper> response = GoNoGoController.getLinkedSubmissions(answer.Id);
            System.Assert(response != null);
        }
    }

    @isTest
    public static void updateAsigneeNotificationTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            GoNoGoController.ResultWrapper response = GoNoGoController.updateAsigneeNotification(true,'IsWon',true,3);
            System.Assert(response != null);
        }
    }

    @isTest
    public static void requestGoNoGoSubmissionTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Opportunity opp = new Opportunity();
            opp.Closedate= System.today();
            opp.Name = 'test';
            opp.StageName = 'IsWon';
            insert opp;
            
            Boolean response = GoNoGoController.requestGoNoGoSubmission(String.valueOf(opp.Id));
            System.Assert(response != null);
        }
    }

    @isTest
    public static void createReminderJobTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Test.startTest();
            GoNoGoController.createReminderJob();
            List<CronTrigger> jobList = [SELECT id from CronTrigger where CronJobDetail.name ='AutoSetup GoNoGoReminderNotificationJob' limit 1];
            System.Assert(jobList.size() == 1);
            Test.stopTest();
        }
    }

    @isTest
    public static void deleteReminderJobTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Test.startTest();
            GoNoGoController.deleteReminderJob();
            List<CronTrigger> jobList = [SELECT id from CronTrigger where CronJobDetail.name ='AutoSetup GoNoGoReminderNotificationJob' limit 1];
            System.Assert(jobList.size() == 0);
            Test.stopTest();
        }
    }
}