MergeField/force-app/main/default/objects/Response_Merge_Field_Mapping__c/Response_Merge_Field_Mapping__c.object-meta.xml
<CustomObject>
    <label>Response Merge Field  Mapping</label>
    <nameField>
        <displayFormat>RMF-{00000}</displayFormat>
        <label>Response Merge Field  Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Merge Fields  Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MergeField/force-app/main/default/objects/Response_Merge_Field_Mapping__c/fields/Merge_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Merge_Field_API_Name__c</fullName>
    <label>Merge Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

MergeField/force-app/main/default/objects/Response_Merge_Field_Mapping__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <type>TextArea</type>
</CustomField>

MergeField/force-app/main/default/classes/NewRelatedFieldMappingController.cls
public with sharing class NewRelatedFieldMappingController {

    @AuraEnabled
    public static Map<String,Object> upsertRecord(String mergeField, String keyWord, String value){
        Map<String,Object> result = new Map<String,Object>();
		try{
            Response_Merge_Field_Mapping__c mergeFieldMapping = new Response_Merge_Field_Mapping__c();
            mergeFieldMapping.Keyword__c = keyWord;
            mergeFieldMapping.Merge_Field_API_Name__c = mergeField;
            mergeFieldMapping.Value__c = value;

            insert mergeFieldMapping;

			result.put('status', 'success');
		    result.put('recordId', String.valueOf(mergeFieldMapping.Id));
		}
		catch(Exception e){
            result.put('status', 'error');
			result.put('errorMessage', e.getMessage());
        }
		return result;
    }
}