GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/GoNoGoSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>To set default configurations for Go/No-Go.</description>
    <label>Loopio Go/No-Go Settings</label>
</CustomObject>

GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/fields/Assignee_Notification__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To store assignee notification enable/disable value.</description>
    <label>Assignee Notification</label>
    <type>Checkbox</type>
</CustomField>

GoNoGo/force-app/main/default/objects/GoNoGoSetting__c/fields/Opportunity_Stage_For_Notification__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage_For_Notification__c</fullName>
    <description>Stores the opportunity stage when to trigger the email notification.</description>
    <label>Opportunity Stage For Notification</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

GoNoGo/force-app/main/default/classes/OpportunityTriggerController.cls
public with sharing class OpportunityTriggerController {

    public static void afterInsert(List<Opportunity> newItems){
        GoNoGoSetting__c gonogosetting = GoNoGoSetting__c.getOrgDefaults();
        if(gonogosetting != null && gonogosetting.Assignee_Notification__c && gonogosetting.Opportunity_Stage_For_Notification__c != null && String.isNotBlank(gonogosetting.Opportunity_Stage_For_Notification__c)){
            Set<Id> oppIds = new Set<Id>();
            String oppStatusToTrigger = gonogosetting.Opportunity_Stage_For_Notification__c;
            for(Opportunity opp : newItems){
                if(opp.StageName != null && String.isNotBlank(opp.StageName) && oppStatusToTrigger.equalsIgnoreCase(opp.StageName)){
                    oppIds.add(opp.Id);
                }
            }
            if(oppIds.size() > 0){
                System.enqueueJob(new SendNotificationQueue(oppIds));
            }
        }
    }
    
    public static void afterUpdate(List<Opportunity> newItems, Map<Id,Opportunity> oldItems){
        GoNoGoSetting__c gonogosetting = GoNoGoSetting__c.getOrgDefaults();
        if(gonogosetting != null && gonogosetting.Assignee_Notification__c && gonogosetting.Opportunity_Stage_For_Notification__c != null && String.isNotBlank(gonogosetting.Opportunity_Stage_For_Notification__c)){
            Set<Id> oppIds = new Set<Id>();
            String oppStatusToTrigger = gonogosetting.Opportunity_Stage_For_Notification__c;
            for(Opportunity opp : newItems){
                if(opp.StageName != null && String.isNotBlank(opp.StageName) && oppStatusToTrigger.equalsIgnoreCase(opp.StageName)){
                    String oldStatus = oldItems.get(opp.Id).StageName;
                    if(oldStatus != opp.StageName){
                        oppIds.add(opp.Id);
                    }
                }
            }
            if(oppIds.size() > 0){
                System.enqueueJob(new SendNotificationQueue(oppIds));
            }
        }
    }
}