MobileExpense/force-app/main/default/objects/hubspot_integration__c/hubspot_integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>stores hubspot integration related data</description>
    <label>Hubspot Integration</label>
</CustomObject>

MobileExpense/force-app/main/default/objects/hubspot_integration__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <description>Stores access token for hubspot integration</description>
    <label>Access Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

MobileExpense/force-app/main/default/objects/hubspot_integration__c/fields/API_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>API_Endpoint__c</fullName>
    <description>Stores hubspot API endpoint.</description>
    <label>API Endpoint</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

MobileExpense/force-app/main/default/objects/hubspot_integration__c/fields/Existing_Companies_Retrieved__c.field-meta.xml
<CustomField>
    <fullName>Existing_Companies_Retrieved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check to retrieve all existing companies or only for that scheduled day</description>
    <label>Existing Companies Retrieved</label>
    <type>Checkbox</type>
</CustomField>

MobileExpense/force-app/main/default/classes/RetrieveCompaniesSchedular.cls
public with sharing class RetrieveCompaniesSchedular implements Schedulable,Database.AllowsCallouts {

    public void execute(SchedulableContext sc) {
        makeCalloutToRetrieveAccounts();
    }
    
    @future(callout=true)
    public static void makeCalloutToRetrieveAccounts(){
        Datetime dateTimeNow = System.now();
        Date dateNow = dateTimeNow.dateGMT();
        dateNow = dateNow.addDays(-1);
        Datetime newDateTime = dateNow;
        String newDateTimeUnix = String.valueOf(newDateTime.getTime());
        hubspot_integration__c integrationSetting = hubspot_integration__c.getOrgDefaults();
        String hubSpotAccessToken, endPoint;
        Boolean existingRetrived;
        if(integrationSetting != null){
            hubSpotAccessToken = integrationSetting.Access_Token__c;
            endPoint = integrationSetting.API_Endpoint__c;
            existingRetrived = integrationSetting.Existing_Companies_Retrieved__c;
        }
        if(hubSpotAccessToken != null && endPoint != null && existingRetrived != null){
            String propertiesString = '"properties": [ "name","domain","phone","address","city","state","zip","country","numberofemployees","type" ]';
            endPoint = endPoint + 'crm/v3/objects/companies/search';
            String reqBody = '';
            if(existingRetrived){
                reqBody = '{"filterGroups":[{"filters":[{"propertyName":"createdate","operator":"GTE","value":"'+newDateTimeUnix+'"}]}],'+propertiesString+'}';
            }
            else{
                reqBody = '{'+propertiesString+'}';
            }
            HttpRequest req = new HttpRequest();
            req.setEndpoint(endPoint);
            req.setHeader('Authorization', 'Bearer ' + hubSpotAccessToken);
            req.setHeader('Accept', 'application/json');
            req.setHeader('Content-type', 'application/json');
            req.setMethod('POST');
            req.setBody(reqBody);
            Http http = new Http();        
            HttpResponse res = new HttpResponse();
            res = http.send(req);
            if(res.getStatusCode() == 200 || res.getStatusCode() == 201){
                String response = res.getBody();
                if(response != null && !String.isBlank(response)){
                    try{
                        HubspotUtility.CompaniesResponse companiesResponse = (HubspotUtility.CompaniesResponse)JSON.deserialize(response, HubspotUtility.CompaniesResponse.class);
                        if(companiesResponse != null && companiesResponse.results != null && companiesResponse.results.size() > 0){
                            List<HubspotUtility.Result> responseResults = companiesResponse.results;
                            System.enqueueJob(new HubspotUtility.CreateAccountsQueue(responseResults));
                        }
                    }
                    catch(Exception e){}
                }
            }
        }
    }
}