GoNoGo/force-app/main/default/objects/Go_No_Go_Configuration__c/Go_No_Go_Configuration__c.object-meta.xml
<CustomObject>
    <description>This object stores a master record of Go/No-Go configuration.</description>
    <label>Go/No-Go Configuration</label>
    <nameField>
        <label>Go/No-Go Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Go/No-Go Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Question_Bank__c/Go_No_Go_Question_Bank__c.object-meta.xml
<CustomObject>
    <description>These records store actual questions which are going to be displayed on the Go/No-Go screen.</description>
    <label>Go/No-Go Question</label>
    <nameField>
        <displayFormat>GNGQB-{0000}</displayFormat>
        <label>Go/No-Go Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Go/No-Go Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Question_Bank__c/fields/Go_No_Go_Section__c.field-meta.xml
<CustomField>
    <fullName>Go_No_Go_Section__c</fullName>
    <description>Master-Detail relation with Go/No-Go Section.</description>
    <label>Go/No-Go Section</label>
    <referenceTo>Go_No_Go_Section__c</referenceTo>
    <relationshipLabel>Go/No-Go Questions</relationshipLabel>
    <relationshipName>Go_No_Go_Question_Banks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Question_Bank__c/fields/Question_Label__c.field-meta.xml
<CustomField>
    <fullName>Question_Label__c</fullName>
    <description>Stores actual question which will be displayed.</description>
    <label>Question Label</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Question_Bank_Scoring__c/Go_No_Go_Question_Bank_Scoring__c.object-meta.xml
<CustomObject>
    <description>Stores scoring for each question.</description>
    <label>Go/No-Go Question Response</label>
    <nameField>
        <displayFormat>GNGQBS-{0000}</displayFormat>
        <label>Go/No-Go Question Scoring Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Go/No-Go Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Question_Bank_Scoring__c/fields/Go_No_Go_Question_Bank__c.field-meta.xml
<CustomField>
    <fullName>Go_No_Go_Question_Bank__c</fullName>
    <description>Master-Detail relation with Go/No-Go Question Bank.</description>
    <label>Go/No-Go Question</label>
    <referenceTo>Go_No_Go_Question_Bank__c</referenceTo>
    <relationshipLabel>Go/No-Go Question Responses</relationshipLabel>
    <relationshipName>Go_No_Go_Question_Bank_Scorings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Question_Bank_Scoring__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>Stores score of the answer.</description>
    <inlineHelpText>The value added to the final Go/No-Go Score when this response is selected. This score cannot exceed the question&apos;s max score.</inlineHelpText>
    <label>Score</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Question_Bank_Scoring__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Expected value of answer (required when Comparison Type of related Go/No-Go Question Bank is Value)</description>
    <label>Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

GoNoGo/force-app/main/default/objects/Go_No_Go_Section__c/Go_No_Go_Section__c.object-meta.xml
<CustomObject>
    <description>There can be multiple sections in a Go/No-Go flow. Each section can consist of different sets of questions. To store the sections, we are going to use this object.</description>
    <label>Go/No-Go Section</label>
    <nameField>
        <label>Go/No-Go Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Go/No-Go Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GoNoGo/force-app/main/default/objects/Go_No_Go_Section__c/fields/Go_No_Go_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Go_No_Go_Configuration__c</fullName>
    <description>Master-Detail relation with Go/No-Go Configuration.</description>
    <label>Go/No-Go Configuration</label>
    <referenceTo>Go_No_Go_Configuration__c</referenceTo>
    <relationshipLabel>Go/No-Go Sections</relationshipLabel>
    <relationshipName>Go_No_Go_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GoNoGo/force-app/main/default/classes/CreateGoNoGoScoresControllerTest.cls
@isTest
public with sharing class CreateGoNoGoScoresControllerTest {
	
    @TestSetup
    static void setup() {
        Profile p = [select id from profile where name='System Administrator'];
        String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        String randomString = '';
        while (randomString.length() < 10) {
           Integer index = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
           randomString += chars.substring(index, index+1);
        }
        String uname = 'test' + randomString + '@testEmail.com';
        User u = new User(alias = 'ftestusr', 
            email='test@loopio.com', 
            emailencodingkey='UTF-8', 
            firstname ='Testing',
            lastname='Testing', 
            languagelocalekey='en_US', 
            localesidkey='en_US', 
            profileid = p.Id, 
            isActive = true,
            timezonesidkey='America/Los_Angeles', 
            username = uname); 
        insert u;
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Go_No_Go_Permission_set'];
        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id);
    }
    
    @isTest
    public static void getExistingScoresForQuestionTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Go_No_Go_Configuration__c config = new Go_No_Go_Configuration__c();
            config.Name = 'Test Config';
            insert config;
            
            Go_No_Go_Section__c section = new Go_No_Go_Section__c();
            section.Name = 'Test Section';
            section.Go_No_Go_Configuration__c = config.Id;
            insert section;
            
            Go_No_Go_Question_Bank__c question = new Go_No_Go_Question_Bank__c();
            question.Go_No_Go_Section__c = section.Id;
            question.Question_Label__c = 'Test Question';
            insert question;
            
            CreateGoNoGoScoresController.ScoringWrapper scoringWrapper = CreateGoNoGoScoresController.getExistingScoresForQuestion(String.valueOf(question.Id));
            System.Assert(scoringWrapper != null);
        }
    }
    
    @isTest
    public static void saveScoringRecordsTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Go_No_Go_Configuration__c config = new Go_No_Go_Configuration__c();
            config.Name = 'Test Config';
            insert config;
            
            Go_No_Go_Section__c section = new Go_No_Go_Section__c();
            section.Name = 'Test Section';
            section.Go_No_Go_Configuration__c = config.Id;
            insert section;
            
            Go_No_Go_Question_Bank__c question = new Go_No_Go_Question_Bank__c();
            question.Go_No_Go_Section__c = section.Id;
            question.Question_Label__c = 'Test Question';
            insert question;
            
            Go_No_Go_Question_Bank_Scoring__c scoring = new Go_No_Go_Question_Bank_Scoring__c();
            scoring.Go_No_Go_Question_Bank__c = question.Id;
            scoring.Score__c = 1;
            scoring.Value__c = 'Yes';
            insert scoring;
            
            CreateGoNoGoScoresController.ScoringRequest scoring1 = new CreateGoNoGoScoresController.ScoringRequest();
            scoring1.score = 1;
            scoring1.value = 'Yes';
            scoring1.scoreId = String.valueOf(scoring.Id);
            
            List<CreateGoNoGoScoresController.ScoringRequest> scoringList = new List<CreateGoNoGoScoresController.ScoringRequest>();
            scoringList.add(scoring1);
            
            CreateGoNoGoScoresController.ResultWrapper response = CreateGoNoGoScoresController.saveScoringRecords(JSON.serialize(scoringList), String.valueOf(question.Id));
            System.Assert(response.isSuccess == true);
        }
    }
    
    @isTest
    public static void deleteScoreRecordTest(){
        String userQuery = 'SELECT Id, lastname FROM User';
        List<User> userList = Database.query(userQuery);
        User u;
        if(userList != null && userList.size() > 0){
            for(User us : userList){
                if(us.get('lastname') != null && String.valueOf(us.get('lastname')).equalsIgnoreCase('Testing')){
                    u = us;
                }
            }
        }
        System.runAs(u) {
            Go_No_Go_Configuration__c config = new Go_No_Go_Configuration__c();
            config.Name = 'Test Config';
            insert config;
            
            Go_No_Go_Section__c section = new Go_No_Go_Section__c();
            section.Name = 'Test Section';
            section.Go_No_Go_Configuration__c = config.Id;
            insert section;
            
            Go_No_Go_Question_Bank__c question = new Go_No_Go_Question_Bank__c();
            question.Go_No_Go_Section__c = section.Id;
            question.Question_Label__c = 'Test Question';
            insert question;
            
            Go_No_Go_Question_Bank_Scoring__c scoring = new Go_No_Go_Question_Bank_Scoring__c();
            scoring.Go_No_Go_Question_Bank__c = question.Id;
            scoring.Score__c = 1;
            scoring.Value__c = 'Yes';
            insert scoring;
            
            Boolean response = CreateGoNoGoScoresController.deleteScoreRecord(String.valueOf(scoring.Id));
            System.Assert(response == true);
        }
    }
}